### ISSUE TITLE
RequestForIRSync missing

### ISSUE THREAD

**Issue by Phamlet** [navikt/eux-rina-irsync#4]
Hi,

I tried running it and got the following error (RINA rest-api.log) : 
`ERROR eu.ec.dgempl.eessi.web.rest.controller.ErrorHandlerController - Cannot submit the document
java.lang.Exception: Cannot submit the document`

`[...]`

`Caused by: java.lang.Exception: cvc-complex-type.2.4.b: The content of element 'sedSYN002:SYN002' is not complete. One of '{RequestForIRSync}' is expected`

	`[...]

	... 114 more`

I runned it on a RINA Fullstack 5.6.4, ssl enabled using command : 
java -Djava.util.concurrent.ForkJoinPool.common.parallelism=16 -jar -Djavax.net.ssl.trustStore=rinasync.jks -Djavax.net.ssl.trustStorePassword=rina eux-rina-irsync-5.6.2-SNAPSHOT.jar

Have you ever encountered this error running the snapshot ?
Thanks

**Comment by torstenk** [comment]
Hi, I think what you experience may happen the very first time you sync a RINA. For that, you have to use RINA Portal and request IR sync manually, stating the version 0.0.1 in the appropiate field. Wait a while, then install the version you got from you AP.
After that, eux-rina-irsync. This is because it relies on an IR version being installed in RINA already. It won't work if no version has ever been installed.
Let me know this fixes your problem.
best regards
Torsten

**Comment by Phamlet** [comment]
Hi,

That's almost it, I finally found out this morning (sorry, I didn't get the time to close the issue).
We already had a version installed. However, this version was installed on a RINA 5.6.2 that we upgraded later to 5.6.4 without installing a new IR version. Upgrading seems to reset the current version.
After I manually sent a request and installed new IR version, I tried again. It works fine now.
Thanks for your help.

Best regards.
